export const FETCH_SETTING_LOADING = "setting/FETCH_SETTING_LOADING";
export const FETCH_SETTING_COMPLETED = "setting/FETCH_SETTING_COMPLETED";
export const FETCH_SETTING_FAILED = "setting/FETCH_SETTING_FAILED";
export const SET_SETTING = "setting/SET_SETTING";
export const SET_ISOPENSAVETOOLBAR = "setting/SET_ISOPENSAVETOOLBAR";
export const SET_ISSAVELOADING = "setting/SET_ISSAVELOADING";
export const SAVE_SETTINGCOMPLETED = "setting/SAVE_SETTINGCOMPLETED";
export const SAVE_SETTINGFAILED = "setting/SAVE_SETTINGFAILED";