export const SET_LOADING = "app/SET_LOADING";
export const FETCH_SHOP_LOADING = "app/FETCH_SHOP_LOADING";
export const FETCH_SHOP_COMPLETED = "app/FETCH_SHOP_COMPLETED";
export const FETCH_SHOP_FAILED = "app/FETCH_SHOP_FAILED";
export const SET_SELECTED_TAB = "app/SET_SELECTED_TAB";
export const SET_IS_NO_CAMPAIGN = "app/SET_IS_NO_CAMPAIGN";
export const SET_IS_CREATING_CAMPAIGN = "app/SET_IS_CREATING_CAMPAIGN";
export const CLICK_BUTTON_NO_CAMPAIGN = "app/CLICK_BUTTON_NO_CAMPAIGN";
