export const FETCH_DESIGN_LOADING = "design/FETCH_DESIGN_LOADING";
export const FETCH_DESIGN_COMPLETED = "design/FETCH_DESIGN_COMPLETED";
export const FETCH_DESIGN_FAILED = "design/FETCH_DESIGN_FAILED";
export const SET_DESIGN = "design/SET_DESIGN";
export const SET_ISOPENSAVETOOLBAR = "design/SET_ISOPENSAVETOOLBAR";
export const SET_ISSAVELOADING = "design/SET_ISSAVELOADING";
export const SAVE_DESIGNCOMPLETED = "design/SAVE_DESIGNCOMPLETED";
export const SAVE_DESIGNFAILED = "design/SAVE_DESIGNFAILED";